-- CreateTable
CREATE TABLE "KeySwitchLog" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "keyId" TEXT NOT NULL,
    "telegramUserId" TEXT,
    "fromServer" TEXT NOT NULL,
    "toServer" TEXT NOT NULL,
    "switchedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_AccessKey" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "outlineKeyId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "email" TEXT,
    "telegramId" TEXT,
    "notes" TEXT,
    "userId" TEXT,
    "serverId" TEXT NOT NULL,
    "accessUrl" TEXT,
    "password" TEXT,
    "port" INTEGER,
    "method" TEXT,
    "dataLimitBytes" BIGINT,
    "usedBytes" BIGINT NOT NULL DEFAULT 0,
    "dataLimitResetStrategy" TEXT NOT NULL DEFAULT 'NEVER',
    "lastDataLimitReset" DATETIME,
    "usageOffset" BIGINT NOT NULL DEFAULT 0,
    "expirationType" TEXT NOT NULL DEFAULT 'NEVER',
    "expiresAt" DATETIME,
    "durationDays" INTEGER,
    "status" TEXT NOT NULL DEFAULT 'ACTIVE',
    "firstUsedAt" DATETIME,
    "lastTrafficAt" DATETIME,
    "lastUsedAt" DATETIME,
    "lastWarningSentAt" DATETIME,
    "expirationWarningStage" TEXT,
    "bandwidthAlertAt80" BOOLEAN NOT NULL DEFAULT false,
    "bandwidthAlertAt90" BOOLEAN NOT NULL DEFAULT false,
    "autoDisableOnLimit" BOOLEAN NOT NULL DEFAULT true,
    "quotaAlertThresholds" TEXT NOT NULL DEFAULT '80,90',
    "quotaAlertsSent" TEXT NOT NULL DEFAULT '[]',
    "disabledAt" DATETIME,
    "disabledOutlineKeyId" TEXT,
    "autoDisableOnExpire" BOOLEAN NOT NULL DEFAULT true,
    "autoArchiveAfterDays" INTEGER NOT NULL DEFAULT 0,
    "archiveAfterAt" DATETIME,
    "autoRenewPolicy" TEXT NOT NULL DEFAULT 'NONE',
    "autoRenewDurationDays" INTEGER,
    "rotationEnabled" BOOLEAN NOT NULL DEFAULT false,
    "rotationInterval" TEXT NOT NULL DEFAULT 'NEVER',
    "lastRotatedAt" DATETIME,
    "nextRotationAt" DATETIME,
    "rotationCount" INTEGER NOT NULL DEFAULT 0,
    "dynamicKeyId" TEXT,
    "prefix" TEXT,
    "subscriptionToken" TEXT,
    "publicSlug" TEXT,
    "subscriptionTheme" TEXT,
    "coverImageType" TEXT,
    "coverImage" TEXT,
    "contactLinks" TEXT,
    "subscriptionWelcomeMessage" TEXT,
    "sharePageEnabled" BOOLEAN NOT NULL DEFAULT true,
    "clientLinkEnabled" BOOLEAN NOT NULL DEFAULT true,
    "telegramDeliveryEnabled" BOOLEAN NOT NULL DEFAULT true,
    "sharePagePasswordHash" TEXT,
    "sharePageAccessExpiresAt" DATETIME,
    "switchesUsed" INTEGER NOT NULL DEFAULT 0,
    "switchesMax" INTEGER NOT NULL DEFAULT 0,
    "serverChangeCount" INTEGER NOT NULL DEFAULT 0,
    "serverChangeLimit" INTEGER NOT NULL DEFAULT 0,
    "lastServerChangeAt" DATETIME,
    "estimatedDevices" INTEGER NOT NULL DEFAULT 0,
    "peakDevices" INTEGER NOT NULL DEFAULT 0,
    "maxDevices" INTEGER,
    "boundDeviceInstallsOnly" BOOLEAN NOT NULL DEFAULT false,
    "deviceLimitExceededAt" DATETIME,
    "deviceLimitWarningSentAt" DATETIME,
    "deviceLimitLastObservedDevices" INTEGER,
    "deviceLimitSuppressedUntil" DATETIME,
    "deviceLimitAutoDisabledAt" DATETIME,
    "owner" TEXT,
    "tags" TEXT NOT NULL DEFAULT '',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "AccessKey_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "AccessKey_serverId_fkey" FOREIGN KEY ("serverId") REFERENCES "Server" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "AccessKey_dynamicKeyId_fkey" FOREIGN KEY ("dynamicKeyId") REFERENCES "DynamicAccessKey" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
INSERT INTO "new_AccessKey" ("accessUrl", "archiveAfterAt", "autoArchiveAfterDays", "autoDisableOnExpire", "autoDisableOnLimit", "autoRenewDurationDays", "autoRenewPolicy", "bandwidthAlertAt80", "bandwidthAlertAt90", "boundDeviceInstallsOnly", "clientLinkEnabled", "contactLinks", "coverImage", "coverImageType", "createdAt", "dataLimitBytes", "dataLimitResetStrategy", "deviceLimitAutoDisabledAt", "deviceLimitExceededAt", "deviceLimitLastObservedDevices", "deviceLimitSuppressedUntil", "deviceLimitWarningSentAt", "disabledAt", "disabledOutlineKeyId", "durationDays", "dynamicKeyId", "email", "estimatedDevices", "expirationType", "expirationWarningStage", "expiresAt", "firstUsedAt", "id", "lastDataLimitReset", "lastRotatedAt", "lastServerChangeAt", "lastTrafficAt", "lastUsedAt", "lastWarningSentAt", "maxDevices", "method", "name", "nextRotationAt", "notes", "outlineKeyId", "owner", "password", "peakDevices", "port", "prefix", "publicSlug", "quotaAlertThresholds", "quotaAlertsSent", "rotationCount", "rotationEnabled", "rotationInterval", "serverChangeCount", "serverChangeLimit", "serverId", "sharePageAccessExpiresAt", "sharePageEnabled", "sharePagePasswordHash", "status", "subscriptionTheme", "subscriptionToken", "subscriptionWelcomeMessage", "tags", "telegramDeliveryEnabled", "telegramId", "updatedAt", "usageOffset", "usedBytes", "userId") SELECT "accessUrl", "archiveAfterAt", "autoArchiveAfterDays", "autoDisableOnExpire", "autoDisableOnLimit", "autoRenewDurationDays", "autoRenewPolicy", "bandwidthAlertAt80", "bandwidthAlertAt90", "boundDeviceInstallsOnly", "clientLinkEnabled", "contactLinks", "coverImage", "coverImageType", "createdAt", "dataLimitBytes", "dataLimitResetStrategy", "deviceLimitAutoDisabledAt", "deviceLimitExceededAt", "deviceLimitLastObservedDevices", "deviceLimitSuppressedUntil", "deviceLimitWarningSentAt", "disabledAt", "disabledOutlineKeyId", "durationDays", "dynamicKeyId", "email", "estimatedDevices", "expirationType", "expirationWarningStage", "expiresAt", "firstUsedAt", "id", "lastDataLimitReset", "lastRotatedAt", "lastServerChangeAt", "lastTrafficAt", "lastUsedAt", "lastWarningSentAt", "maxDevices", "method", "name", "nextRotationAt", "notes", "outlineKeyId", "owner", "password", "peakDevices", "port", "prefix", "publicSlug", "quotaAlertThresholds", "quotaAlertsSent", "rotationCount", "rotationEnabled", "rotationInterval", "serverChangeCount", "serverChangeLimit", "serverId", "sharePageAccessExpiresAt", "sharePageEnabled", "sharePagePasswordHash", "status", "subscriptionTheme", "subscriptionToken", "subscriptionWelcomeMessage", "tags", "telegramDeliveryEnabled", "telegramId", "updatedAt", "usageOffset", "usedBytes", "userId" FROM "AccessKey";
DROP TABLE "AccessKey";
ALTER TABLE "new_AccessKey" RENAME TO "AccessKey";
CREATE UNIQUE INDEX "AccessKey_subscriptionToken_key" ON "AccessKey"("subscriptionToken");
CREATE UNIQUE INDEX "AccessKey_publicSlug_key" ON "AccessKey"("publicSlug");
CREATE INDEX "AccessKey_status_idx" ON "AccessKey"("status");
CREATE INDEX "AccessKey_status_lastTrafficAt_idx" ON "AccessKey"("status", "lastTrafficAt");
CREATE INDEX "AccessKey_expiresAt_idx" ON "AccessKey"("expiresAt");
CREATE INDEX "AccessKey_userId_idx" ON "AccessKey"("userId");
CREATE INDEX "AccessKey_serverId_idx" ON "AccessKey"("serverId");
CREATE UNIQUE INDEX "AccessKey_serverId_outlineKeyId_key" ON "AccessKey"("serverId", "outlineKeyId");
CREATE TABLE "new_DynamicAccessKey" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "type" TEXT NOT NULL DEFAULT 'SELF_MANAGED',
    "email" TEXT,
    "telegramId" TEXT,
    "notes" TEXT,
    "switchesUsed" INTEGER NOT NULL DEFAULT 0,
    "switchesMax" INTEGER NOT NULL DEFAULT 0,
    "userId" TEXT,
    "serverTagsJson" TEXT NOT NULL DEFAULT '[]',
    "dataLimitBytes" BIGINT,
    "usedBytes" BIGINT NOT NULL DEFAULT 0,
    "bandwidthAlertAt80" BOOLEAN NOT NULL DEFAULT false,
    "bandwidthAlertAt90" BOOLEAN NOT NULL DEFAULT false,
    "quotaAlertThresholds" TEXT NOT NULL DEFAULT '80,90',
    "quotaAlertsSent" TEXT NOT NULL DEFAULT '[]',
    "autoDisableOnLimit" BOOLEAN NOT NULL DEFAULT true,
    "dataLimitResetStrategy" TEXT NOT NULL DEFAULT 'NEVER',
    "lastDataLimitReset" DATETIME,
    "usageOffset" BIGINT NOT NULL DEFAULT 0,
    "expiresAt" DATETIME,
    "durationDays" INTEGER,
    "expirationType" TEXT NOT NULL DEFAULT 'NEVER',
    "status" TEXT NOT NULL DEFAULT 'ACTIVE',
    "firstUsedAt" DATETIME,
    "lastTrafficAt" DATETIME,
    "estimatedDevices" INTEGER NOT NULL DEFAULT 0,
    "peakDevices" INTEGER NOT NULL DEFAULT 0,
    "maxDevices" INTEGER,
    "boundDeviceInstallsOnly" BOOLEAN NOT NULL DEFAULT false,
    "deviceLimitExceededAt" DATETIME,
    "deviceLimitWarningSentAt" DATETIME,
    "deviceLimitLastObservedDevices" INTEGER,
    "deviceLimitSuppressedUntil" DATETIME,
    "deviceLimitAutoDisabledAt" DATETIME,
    "lastWarningSentAt" DATETIME,
    "expirationWarningStage" TEXT,
    "dynamicUrl" TEXT,
    "publicSlug" TEXT,
    "prefix" TEXT,
    "method" TEXT NOT NULL DEFAULT 'chacha20-ietf-poly1305',
    "owner" TEXT,
    "tags" TEXT NOT NULL DEFAULT '',
    "loadBalancerAlgorithm" TEXT NOT NULL DEFAULT 'IP_HASH',
    "preferredServerIdsJson" TEXT NOT NULL DEFAULT '[]',
    "preferredCountryCodesJson" TEXT NOT NULL DEFAULT '[]',
    "preferredServerWeightsJson" TEXT NOT NULL DEFAULT '{}',
    "preferredCountryWeightsJson" TEXT NOT NULL DEFAULT '{}',
    "preferredRegionMode" TEXT NOT NULL DEFAULT 'PREFER',
    "sessionStickinessMode" TEXT NOT NULL DEFAULT 'DRAIN',
    "drainGraceMinutes" INTEGER NOT NULL DEFAULT 20,
    "lastSelectedKeyIndex" INTEGER NOT NULL DEFAULT 0,
    "lastResolvedAccessKeyId" TEXT,
    "lastResolvedServerId" TEXT,
    "lastResolvedAt" DATETIME,
    "pinnedAccessKeyId" TEXT,
    "pinnedServerId" TEXT,
    "pinnedAt" DATETIME,
    "pinExpiresAt" DATETIME,
    "subscriptionTheme" TEXT,
    "coverImageType" TEXT,
    "coverImage" TEXT,
    "contactLinks" TEXT,
    "subscriptionWelcomeMessage" TEXT,
    "sharePageEnabled" BOOLEAN NOT NULL DEFAULT true,
    "rotationEnabled" BOOLEAN NOT NULL DEFAULT false,
    "rotationInterval" TEXT NOT NULL DEFAULT 'NEVER',
    "rotationTriggerMode" TEXT NOT NULL DEFAULT 'SCHEDULED',
    "rotationUsageThresholdPercent" INTEGER NOT NULL DEFAULT 85,
    "rotateOnHealthFailure" BOOLEAN NOT NULL DEFAULT false,
    "lastRotatedAt" DATETIME,
    "nextRotationAt" DATETIME,
    "rotationCount" INTEGER NOT NULL DEFAULT 0,
    "lastRoutingAlertAt" DATETIME,
    "autoClearStalePins" BOOLEAN NOT NULL DEFAULT true,
    "autoFallbackToPrefer" BOOLEAN NOT NULL DEFAULT false,
    "autoSkipUnhealthy" BOOLEAN NOT NULL DEFAULT false,
    "routingAlertRules" TEXT,
    "welcomeMessage" TEXT,
    "appliedTemplateId" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "DynamicAccessKey_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "DynamicAccessKey_appliedTemplateId_fkey" FOREIGN KEY ("appliedTemplateId") REFERENCES "DynamicKeyTemplate" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
INSERT INTO "new_DynamicAccessKey" ("appliedTemplateId", "autoClearStalePins", "autoDisableOnLimit", "autoFallbackToPrefer", "autoSkipUnhealthy", "bandwidthAlertAt80", "bandwidthAlertAt90", "boundDeviceInstallsOnly", "contactLinks", "coverImage", "coverImageType", "createdAt", "dataLimitBytes", "dataLimitResetStrategy", "deviceLimitAutoDisabledAt", "deviceLimitExceededAt", "deviceLimitLastObservedDevices", "deviceLimitSuppressedUntil", "deviceLimitWarningSentAt", "drainGraceMinutes", "durationDays", "dynamicUrl", "email", "estimatedDevices", "expirationType", "expirationWarningStage", "expiresAt", "firstUsedAt", "id", "lastDataLimitReset", "lastResolvedAccessKeyId", "lastResolvedAt", "lastResolvedServerId", "lastRotatedAt", "lastRoutingAlertAt", "lastSelectedKeyIndex", "lastTrafficAt", "lastWarningSentAt", "loadBalancerAlgorithm", "maxDevices", "method", "name", "nextRotationAt", "notes", "owner", "peakDevices", "pinExpiresAt", "pinnedAccessKeyId", "pinnedAt", "pinnedServerId", "preferredCountryCodesJson", "preferredCountryWeightsJson", "preferredRegionMode", "preferredServerIdsJson", "preferredServerWeightsJson", "prefix", "publicSlug", "quotaAlertThresholds", "quotaAlertsSent", "rotateOnHealthFailure", "rotationCount", "rotationEnabled", "rotationInterval", "rotationTriggerMode", "rotationUsageThresholdPercent", "routingAlertRules", "serverTagsJson", "sessionStickinessMode", "sharePageEnabled", "status", "subscriptionTheme", "subscriptionWelcomeMessage", "tags", "telegramId", "type", "updatedAt", "usageOffset", "usedBytes", "userId", "welcomeMessage") SELECT "appliedTemplateId", "autoClearStalePins", "autoDisableOnLimit", "autoFallbackToPrefer", "autoSkipUnhealthy", "bandwidthAlertAt80", "bandwidthAlertAt90", "boundDeviceInstallsOnly", "contactLinks", "coverImage", "coverImageType", "createdAt", "dataLimitBytes", "dataLimitResetStrategy", "deviceLimitAutoDisabledAt", "deviceLimitExceededAt", "deviceLimitLastObservedDevices", "deviceLimitSuppressedUntil", "deviceLimitWarningSentAt", "drainGraceMinutes", "durationDays", "dynamicUrl", "email", "estimatedDevices", "expirationType", "expirationWarningStage", "expiresAt", "firstUsedAt", "id", "lastDataLimitReset", "lastResolvedAccessKeyId", "lastResolvedAt", "lastResolvedServerId", "lastRotatedAt", "lastRoutingAlertAt", "lastSelectedKeyIndex", "lastTrafficAt", "lastWarningSentAt", "loadBalancerAlgorithm", "maxDevices", "method", "name", "nextRotationAt", "notes", "owner", "peakDevices", "pinExpiresAt", "pinnedAccessKeyId", "pinnedAt", "pinnedServerId", "preferredCountryCodesJson", "preferredCountryWeightsJson", "preferredRegionMode", "preferredServerIdsJson", "preferredServerWeightsJson", "prefix", "publicSlug", "quotaAlertThresholds", "quotaAlertsSent", "rotateOnHealthFailure", "rotationCount", "rotationEnabled", "rotationInterval", "rotationTriggerMode", "rotationUsageThresholdPercent", "routingAlertRules", "serverTagsJson", "sessionStickinessMode", "sharePageEnabled", "status", "subscriptionTheme", "subscriptionWelcomeMessage", "tags", "telegramId", "type", "updatedAt", "usageOffset", "usedBytes", "userId", "welcomeMessage" FROM "DynamicAccessKey";
DROP TABLE "DynamicAccessKey";
ALTER TABLE "new_DynamicAccessKey" RENAME TO "DynamicAccessKey";
CREATE UNIQUE INDEX "DynamicAccessKey_dynamicUrl_key" ON "DynamicAccessKey"("dynamicUrl");
CREATE UNIQUE INDEX "DynamicAccessKey_publicSlug_key" ON "DynamicAccessKey"("publicSlug");
CREATE INDEX "DynamicAccessKey_userId_idx" ON "DynamicAccessKey"("userId");
CREATE INDEX "DynamicAccessKey_status_lastTrafficAt_idx" ON "DynamicAccessKey"("status", "lastTrafficAt");
CREATE INDEX "DynamicAccessKey_appliedTemplateId_idx" ON "DynamicAccessKey"("appliedTemplateId");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
