export { handleTelegramUpdate } from '@/lib/services/telegram-bot-dispatch';

export {
  approveTelegramOrder,
  approveTelegramPremiumSupportRequest,
  approveTelegramServerChangeRequest,
  createAccessKeyTelegramConnectLink,
  createDynamicKeyTelegramConnectLink,
  dismissTelegramPremiumSupportRequest,
  replyTelegramPremiumSupportRequest,
  rejectTelegramOrder,
  rejectTelegramServerChangeRequest,
  runTelegramSalesOrderCycle,
  runTelegramSalesDigestCycle,
  sendAccessKeyLifecycleTelegramNotification,
  sendAccessKeyRenewalReminder,
  sendAccessKeySharePageToTelegram,
  sendAccessKeySupportMessage,
  sendAdminAlert,
  sendDynamicKeySharePageToTelegram,
  sendRenewalRequestToAdmins,
  sendServerIssueNoticeToTelegram,
  sendTelegramDigestToAdmins,
  sendTelegramMessage,
  sendTelegramOrderReceiptConfirmation,
  type TelegramUpdate,
  updateTelegramOrderDraft,
  handleTelegramPremiumSupportRequest,
  getTelegramConfig,
} from '@/lib/services/telegram-bot-core';
